// <auto-generated />
using System;
using Construction_ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Construction_ERP.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250918062716_Construction_ERP")]
    partial class Construction_ERP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Construction_Management_Project_Model.Models.Bank_Model", b =>
                {
                    b.Property<int>("Bank_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bank_Id"), 1L, 1);

                    b.Property<int?>("Acflag")
                        .HasColumnType("int");

                    b.Property<string>("Bank_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saas_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Bank_Id");

                    b.ToTable("Bank_Table");
                });

            modelBuilder.Entity("Construction_Management_Project_Model.Models.EmployeeMaster_Model", b =>
                {
                    b.Property<int>("Emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emp_id"), 1L, 1);

                    b.Property<string>("Emp_Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Bank_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_id");

                    b.ToTable("Employee_Table");
                });

            modelBuilder.Entity("Construction_Management_Project_Model.Models.Roll_Model", b =>
                {
                    b.Property<int>("Roll_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Roll_Id"), 1L, 1);

                    b.Property<int?>("Acflag")
                        .HasColumnType("int");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roll_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Saas_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Roll_Id");

                    b.ToTable("Roll_Table");
                });

            modelBuilder.Entity("Construction_Management_Project_Model.Models.User_Registration_Model", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"), 1L, 1);

                    b.Property<string>("Ac_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Employee_id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Roll_Id")
                        .HasColumnType("int");

                    b.Property<string>("Token_key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Updated_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("User_Registration_Table");
                });
#pragma warning restore 612, 618
        }
    }
}
